name: zikzak_useragent_example
description: "Demonstrates how to use the zikzak_useragent plugin."
publish_to: "none"

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

  zikzak_useragent:
    path: ../

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  zikzak_useragent_platform_interface:
    path: ../../zikzak_useragent_platform_interface
  zikzak_useragent_android:
    path: ../../zikzak_useragent_android
  zikzak_useragent_ios:
    path: ../../zikzak_useragent_ios
  zikzak_useragent_macos:
    path: ../../zikzak_useragent_macos

flutter:
  uses-material-design: true
