name: zikzak_useragent_example
description: "Demonstrates how to use the zikzak_useragent plugin."
publish_to: "none"

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  zikzak_useragent:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
