name: zikzak_useragent_platform_interface
description: A common platform interface for the zikzak_useragent plugin.
repository: https://github.com/arrrrny/zikzak_useragent/tree/main/zikzak_useragent_platform_interface
version: 1.1.0

environment:
  sdk: "^3.3.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
