name: zikzak_useragent_android
description: The Android implementation of zikzak_useragent.
repository: https://github.com/arrrrny/zikzak_useragent/tree/main/zikzak_useragent_android
version: 1.1.0

environment:
  sdk: "^3.3.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  zikzak_useragent_platform_interface: ^1.1.0

flutter:
  plugin:
    implements: zikzak_useragent
    platforms:
      android:
        package: com.strysk.zikzak_useragent_android.zikzak_useragent_android
        pluginClass: ZikzakUserAgentPlugin
        dartPluginClass: ZikzakUserAgentAndroid
