name: zikzak_useragent_android
description: The Android implementation of zikzak_useragent.
repository: https://github.com/arrrrny/zikzak_useragent/tree/main/zikzak_useragent_android
version: 1.1.5

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

  zikzak_useragent_platform_interface: ^1.1.5

flutter:
  plugin:
    implements: zikzak_useragent
    platforms:
      android:
        package: dev.zuzu.zikzak_useragent_android.zikzak_useragent_android
        pluginClass: ZikzakUserAgentPlugin
        dartPluginClass: ZikzakUserAgentAndroid
