name: webview_useragent
description: "A new Flutter plugin project."
version: 1.0.0
homepage:

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  webview_useragent_ios:
    path: ../webview_useragent_ios
  webview_useragent_platform_interface:
    path: ../webview_useragent_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.strysk.webview_useragent.webview_useragent
        pluginClass: WebviewUserAgentPlugin
      ios:
        default_package: webview_useragent_ios
